 
version: '3'
services:
  treasurytgbot:
    build:
      context: tgbot
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: treasurybotdb
      MONGODB_USERNAME: mongorootuser
      MONGODB_PASSWORD: TrsryPswdRoot
      MONGODB_HOSTNAME: mongodb
      MONGODB_PORT: 27017
    links:
      - mongodb
  
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongorootuser
      MONGO_INITDB_ROOT_PASSWORD: TrsryPswdRoot
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodb/data:/data/db
